---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "group-sync-operator"
  namespace: "group-sync-operator"
spec:
  channel: "alpha"
  installPlanApproval: "Automatic"
  source: "community-operators"
  sourceNamespace: "openshift-marketplace"
  name: "group-sync-operator"
