apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret   # https://external-secrets.io/v0.9.1/api/clusterexternalsecret/
metadata:
  name: oauth-external-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  externalSecretName: "{{ app_client_secret }}"
  namespaceSelector:
    matchLabels: 
      secrets: {{ app_client_secret }}
  refreshTime: "15s" # How often this secret is synchronized
  externalSecretSpec:
    refreshInterval: "1h"
    secretStoreRef:
      name: azure-secret-store
      kind: ClusterSecretStore
    target: # Our target Kubernetes Secret
      name: {{ app_client_secret }} # Name of the secret to create.  If not present, then the secretKey field under data will be used
      creationPolicy: Owner # This will create the secret if it doesn't exist
    data:
      - secretKey: clientSecret
        remoteRef:
          key: {{ app_client_secret }} # Secret Nanem in Azure KV 