apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets-operator
  namespace: {{ external_secret_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: external-secrets-operator
  source: external-secrets-operator-catalog
  sourceNamespace: {{ external_secret_namespace }}
