apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore  # https://external-secrets.io/v0.9.1/provider/azure-key-vault/
metadata:
  name: azure-secret-store
  namespace: {{ external_secret_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "{{ app_tenant_id }}"
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "{{ vault_instance_url }}"
      authSecretRef:
        # points to the secret (azure-secret) that contains the CLietnID and ClientSecret for the azure service principal account.
        # Note, this secret must be created in advance... before the gitops runs.  
        clientId:
          name: azure-secret
          namespace: {{ external_secret_namespace }}
          key: ClientID
        clientSecret:
          name: azure-secret
          namespace: {{ external_secret_namespace }}
          key: ClientSecret